global:
  scrape_interval: 15s

scrape_configs:
  - job_name: otelcol
    dns_sd_configs:
      - names: [loadbal, worker]
        type: A
        port: 8888
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: role
